name: Run Unit tests
on:
  pull_request:
    branches: ["dev"]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install pnpm
        run: npm install -g pnpm@7.18.2
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
